-- ---------------------------------------------------------------------------
-- Referencia de esquema (NO se ejecuta automáticamente).
-- Hibernate gestiona el DDL en entornos dev/test vía 'spring.jpa.hibernate.ddl-auto=update'.
-- Mantener este script solo como documentación / bootstrap manual.
-- Última sincronización: after rebase con DTOs y refactor entidades (User, Exercise, Routine, RoutineExercise)
-- ---------------------------------------------------------------------------

-- Drop order: dependents first (DB kept in Spanish)
DROP TABLE IF EXISTS notificacion_seguidor_coach;
DROP TABLE IF EXISTS notificacion;
DROP TABLE IF EXISTS blocks;
DROP TABLE IF EXISTS follows;
DROP TABLE IF EXISTS rutina_ejercicio;
DROP TABLE IF EXISTS ejercicio;
DROP TABLE IF EXISTS rutinas_guardadas;
DROP TABLE IF EXISTS rutinas;
DROP TABLE IF EXISTS usuario_GymTracker;

CREATE TABLE usuario_GymTracker (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario VARCHAR(60) NOT NULL,
    username_usuario VARCHAR(60) NOT NULL UNIQUE,
    contrasena_usuario VARCHAR(60) NOT NULL,
    rol VARCHAR(20) NOT NULL,
    avatar_url VARCHAR(255),

    premium BOOLEAN DEFAULT FALSE,

    bloqueado BOOLEAN DEFAULT FALSE NOT NULL,

    email VARCHAR(100),

    first_name VARCHAR(60),
    last_name VARCHAR(60),

    weight DECIMAL(5,2),
    height DECIMAL(5,2),
    age INT,
    gender VARCHAR(20)
);


CREATE TABLE rutinas (
    id_rutina BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rutina VARCHAR(60) NOT NULL,
    id_usuario BIGINT NOT NULL,
    visible BOOLEAN DEFAULT TRUE NOT NULL,
    estado VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    bloqueado BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT fk_rutina_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario_GymTracker(id_usuario)
        ON DELETE CASCADE
);

CREATE TABLE ejercicio (
    id_ejercicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ejercicio VARCHAR(60) NOT NULL,
    descripcion VARCHAR(255),
    musculos VARCHAR(60),
    equipamiento VARCHAR(100),
    imagen_url VARCHAR(500),
    estado VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    bloqueado BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE rutina_ejercicio (
    id_rutina_ejercicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rutina BIGINT NOT NULL,
    id_ejercicio BIGINT NOT NULL,
    num_series INT NOT NULL,
    num_repeticiones INT NOT NULL,
    peso DECIMAL(6,2),
    CONSTRAINT fk_rutina_ejercicio_rutina FOREIGN KEY (id_rutina)
        REFERENCES rutinas(id_rutina) ON DELETE CASCADE,
    CONSTRAINT fk_rutina_ejercicio_ejercicio FOREIGN KEY (id_ejercicio)
        REFERENCES ejercicio(id_ejercicio) ON DELETE CASCADE
);

CREATE TABLE rutinas_guardadas (
    id_rutina_guardada BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    id_rutina BIGINT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT uq_rutinas_guardadas UNIQUE (id_usuario, id_rutina),
    CONSTRAINT fk_rg_usuario FOREIGN KEY (id_usuario) REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_rg_rutina FOREIGN KEY (id_rutina) REFERENCES rutinas(id_rutina) ON DELETE CASCADE
);

-- Notifications (Spanish)
CREATE TABLE notificacion (
    id_notificacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_destinatario BIGINT NOT NULL,
    tipo VARCHAR(40) NOT NULL,
    mensaje VARCHAR(300),
    leido BOOLEAN,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_notif_usuario FOREIGN KEY (id_destinatario)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE
);

-- Notification for followed coach (Spanish)
CREATE TABLE notificacion_seguidor_coach (
    id_notificacion_followed BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rutina VARCHAR(60) NOT NULL,
    id_usuario BIGINT NOT NULL,
    id_coach BIGINT NOT NULL,
    leido BOOLEAN,
    fecha_creacion TIMESTAMP NOT NULL,
    CONSTRAINT fk_nfc_user FOREIGN KEY (id_usuario)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_nfc_coach FOREIGN KEY (id_coach)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE
);

-- Follows table
CREATE TABLE follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL,
    coach_id BIGINT NOT NULL,
    CONSTRAINT fk_follows_follower FOREIGN KEY (follower_id)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_follows_coach FOREIGN KEY (coach_id)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE,
    CONSTRAINT uq_follows UNIQUE (follower_id, coach_id)
);

-- Blocks table
CREATE TABLE blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT NOT NULL,
    blocked_id BIGINT NOT NULL,
    blocked_at TIMESTAMP,
    CONSTRAINT fk_blocks_blocker FOREIGN KEY (blocker_id)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_blocks_blocked FOREIGN KEY (blocked_id)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE,
    CONSTRAINT uq_blocks UNIQUE (blocker_id, blocked_id)
);

CREATE TABLE notificacion_fin_racha (
    id_notificacion_racha BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_usuario BIGINT NOT NULL,

    dias_racha INT NOT NULL,
    fecha_limite TIMESTAMP NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    mensaje VARCHAR(300),
    leido BOOLEAN DEFAULT FALSE,

    CONSTRAINT fk_nfr_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario_GymTracker(id_usuario) ON DELETE CASCADE
);
